export const ABOUT_TEXT = [
  'David Andrew Leo Fincher',
  'is an American filmmaker',
  '\n',
  'His films, most of which are',
  'psychological thrillers, have',
  'collectively grossed over $2.1',
  'billion worldwide and',
  'have received 40 Academy',
  'Award nominations',
  '\n',
  '\n',
  '\n',
  'Filmography',
  '\n',
  '\tAlien 3',
  '\t1992',
  '\n',
  '\tSe7en',
  '\t1995',
  '\n',
  '\tThe Game',
  '\t1997',
  '\n',
  '\tFight club',
  '\t1999',
  '\n',
  '\tPanic Room',
  '\t2002',
  '\n',
  '\tZodiac',
  '\t2007',
  '\n',
  '\tThe curious case of Benjamin Button',
  '\t2008',
  '\n',
  '\tThe Social Network',
  '\t2010',
  '\n',
  '\tThe Girl with the Dragon Tattoo',
  '\t2011',
  '\n',
  '\tGone Girl',
  '\t2014',
  '\n',
  '\tMank',
  '\t2020',
  '\n',
  '\tThe Killer',
  '\t2023',
];
